
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/app
      - NCC_USER=${NCC_USER}
      - NCC_HOST=${NCC_HOST}
      - NCC_PRIVATE_KEY_PATH=${NCC_PRIVATE_KEY_PATH}

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
