name: projectastra
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0" # Example of a common Flutter project Dart SDK constraint, adjust if needed or keep ^3.7.2 if appropriate

dependencies:
  flutter:
    sdk: flutter

  # === REPLACE 'any' with specific versions from pubspec.lock after successful 'pub get' ===
  table_calendar: any # e.g., ^3.1.0
  http: ^1.4.0 # e.g., ^1.2.1
  flutter_markdown: any # e.g., ^0.7.3
  # REMOVE: markdown: ^7.2.2
  flutter_markdown_latex: any # e.g., ^3.0.2
  highlight: any # e.g., ^0.7.0
  flutter_math_fork: any # e.g., ^0.7.2 (or let flutter_markdown_latex handle it)
  flutter_inappwebview: ^6.0.0 # Add this line
  flutter_quill: ^9.0.0 # Add this line
  flutter_code_editor: ^0.3.0 # Add this line
  googleapis: ^13.1.0 # Add this line
  googleapis_auth: ^1.6.0 # Add this line
  cupertino_icons: any # e.g., ^1.0.8
  lucide_icons: any # e.g., ^0.395.0 or similar latest

  # Hive dependencies (these are good as they are)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  firebase_core_platform_interface: ^5.4.0
  #desktop_webview_auth: ^0.0.15
  cloud_firestore: ^5.6.8
  google_sign_in_all_platforms: any
  url_launcher: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 # Corrected to a likely valid version
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/AstraPfP.png
    - assets/AstraLogo.png
    - assets/UserProfile.png
