name: projectastra
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  provider: ^6.1.2
  intl: 0.20.2

  # Firebase & Auth
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  google_sign_in_all_platforms: ^1.1.0
  cloud_firestore: ^5.6.8
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0

  # Backend Communication
  http: ^1.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Feature-specific
  table_calendar: ^3.2.0
  flutter_markdown: ^0.7.7+1
  flutter_markdown_latex: ^0.3.4
  highlight: ^0.7.0
  flutter_math_fork: ^0.7.4
  webview_flutter: ^4.7.0
  flutter_quill: 11.4.2
  flutter_code_editor: ^0.3.4
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  url_launcher: ^6.3.1
  hotkey_manager: 0.2.3
  llama_cpp_dart: ^0.1.0 # For local LLM inference

  # Finance Module Additions
  plaid_flutter: ^3.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/AstriumLogo.png
    - assets/UserProfile.png