// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaPqkPrwPqLZB6jpy8TechDoAkL4LAjMw',
    appId: '1:921780484273:web:11d0256bdda7eee73c0a90',
    messagingSenderId: '921780484273',
    projectId: 'astraai-53147',
    authDomain: 'astraai-53147.firebaseapp.com',
    storageBucket: 'astraai-53147.firebasestorage.app',
    measurementId: 'G-S63MJZ906D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjOJV7KWAuVHTw31k7Rn5w8HtUsR3F6JM',
    appId: '1:921780484273:android:0287bac5b0a7f9483c0a90',
    messagingSenderId: '921780484273',
    projectId: 'astraai-53147',
    storageBucket: 'astraai-53147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDNV03pnmqrJlsTnkAp3XS_bpc_pQOkqY',
    appId: '1:921780484273:ios:4a5d865f86bd9cf23c0a90',
    messagingSenderId: '921780484273',
    projectId: 'astraai-53147',
    storageBucket: 'astraai-53147.firebasestorage.app',
    androidClientId: '921780484273-kq2f2uj9pqp00ie8nsresan4kds5u4n9.apps.googleusercontent.com',
    iosClientId: '921780484273-td08h2h6r5atrnf0pf96gacfd2ulafom.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectastra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDNV03pnmqrJlsTnkAp3XS_bpc_pQOkqY',
    appId: '1:921780484273:ios:4a5d865f86bd9cf23c0a90',
    messagingSenderId: '921780484273',
    projectId: 'astraai-53147',
    storageBucket: 'astraai-53147.firebasestorage.app',
    androidClientId: '921780484273-kq2f2uj9pqp00ie8nsresan4kds5u4n9.apps.googleusercontent.com',
    iosClientId: '921780484273-td08h2h6r5atrnf0pf96gacfd2ulafom.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectastra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaPqkPrwPqLZB6jpy8TechDoAkL4LAjMw',
    appId: '1:921780484273:web:ed5d63091a3674403c0a90',
    messagingSenderId: '921780484273',
    projectId: 'astraai-53147',
    authDomain: 'astraai-53147.firebaseapp.com',
    storageBucket: 'astraai-53147.firebasestorage.app',
    measurementId: 'G-EC3PY27T1E',
  );
}
