import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart'; // Import Hive Flutter for initialization
import 'package:provider/provider.dart'; // For ChangeNotifierProvider
import 'package:hotkey_manager/hotkey_manager.dart';

import 'package:projectastra/models/chat_models.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart';
import 'services/auth_service.dart'; // Your AuthService import
import 'widgets/auth/auth_gate.dart'; // Import AuthGate for authentication handling
import 'package:projectastra/theme/app_themes.dart';
import 'package:projectastra/theme/theme_notifier.dart';

// Define the box name as a constant for easy reuse
const String chatMessagesBoxName = 'chatMessagesBox';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await hotKeyManager.unregisterAll();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  final AuthService authService = AuthService();

  await Hive.initFlutter();

  if (!Hive.isAdapterRegistered(MessageTypeAdapter().typeId)) {
    Hive.registerAdapter(MessageTypeAdapter());
  }
  if (!Hive.isAdapterRegistered(ChatMessageAdapter().typeId)) {
    Hive.registerAdapter(ChatMessageAdapter());
  }

  await Hive.openBox<ChatMessage>(chatMessagesBoxName);

  // Initialize ThemeNotifier with the default dark theme
  final initialThemeName = 'Dark Astra'; // Or 'Dark Theme' based on your theme.txt
  final initialThemeData = AppThemes.availableThemes[initialThemeName]!;

  runApp(
    ChangeNotifierProvider(
      create: (_) => ThemeNotifier(initialThemeData, initialThemeName, AppThemes.availableThemes),
      child: MyApp(authService: authService),
    ),
  );
}

class MyApp extends StatelessWidget {
  final AuthService authService;

  const MyApp({super.key, required this.authService});

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeNotifier>(
      builder: (context, themeNotifier, child) {
        return MaterialApp(
          title: 'Astrium Suites',
          theme: themeNotifier.currentTheme,
          home: AuthGate(authService: authService),
          debugShowCheckedModeBanner: false,
        );
      },
    );
  }
}
